<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DashboardTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->authenticate();
    }

    public function authenticate(string $guard = null)
    {
        $user = User::factory()->create();
        $this->actingAs($user, $guard);
    }

    public function test_dashboard_page_render_with_auth()
    {
        //$this->authenticate();

        $response = $this->get('/');
        $response->assertStatus(200);
    }

    public function test_dashboard_render_view_file_with_auth()
    {
        //$this->authenticate();

        $response = $this->get('/');
        $response->assertSuccessful();
        $response->assertViewIs('pages.dashboard');

    }
}
